### ISSUE TITLE
Production demo site is 404 unavailable 

### ISSUE THREAD

**Issue by IO-Fire** [bloggrify/demo-mistral#1]
Visiting the [https://mistral.bloggrify.com](https://mistral.bloggrify.com) site results in a **Page Not Found** error for all pages.

### Example

[https://mistral.bloggrify.com/](https://mistral.bloggrify.com/)

## Potential Fix

Re-deploy the production site on Netlify.

**Comment by hlassiege** [comment]
good catch
It's the same problem for minimalist.bloggrify.com
Due to some changes in the deployment script on netlify.
